describe("Pokemons", function () {
    require("./constructor")
    require("./mintPokemon")
    require("./checkAvailableEvolve")
    require("./evolvePokemon")
    require("./setMaxSupply")
    require("./setMintFee")
    require("./setEvolveLevelFee")
    require("./setNewLevelContract")
    require("./setNewStonesContract")
    require("./withdrawETH")
    require("./uri")
})
